// =====================================================================
//  HODGE_ENGINE_v3   (Sparse / Tensorial)
//  Integral Hodge Conjecture verifier for even-dimensional Fermat varieties.
//  Method: Degtyarev-Shimada (arXiv:1405.4683), computational criterion (Sec.5).
//
//  Fermat  X_n^m : x_0^m + ... + x_{n+1}^m = 0   (n even, m>2),  d = n/2.
//  Standard linear d-spaces generate the FULL integral Hodge lattice
//   <=> L(X) primitive in H_n(X)  <=> Tors(H_n(X)/L(X))=0
//   <=> dim_C B_K == dim_{F_p} B_K  for every prime p | m,
//  where B_K = Rbar/(rho_J : J),  Rbar = k[t_1..t_{n+1}]/(phi(t_i)),
//        phi = 1+t+...+t^{m-1},   dim_k Rbar = (m-1)^{n+1} =: DIM.
//
//  When m is prime, primitivity == Integral Hodge Conjecture for X.
//
//  ---- v3 engineering over v2 ----
//  (1) TENSORIAL rho_J: a partition splits the n+2 indices into DISJOINT pairs,
//      so rho_J = tensor product of single-pair factors rho(t_j,t_k).
//      Built directly as a sparse vector in O(#nonzeros), NO dense polynomial
//      multiplication (v2's O(DIM^2) wall is gone).
//  (2) SPARSE incremental Gaussian elimination over F_p with pivot map col->row;
//      the ideal span is generated by CLOSURE of the base rho_J under the n+1
//      variable-shift operators (mult by t_v), so we never materialize DIM*parts
//      dense rows. dim B_K = DIM - rank.
//  (3) GUARDS: abort with a clear message if DIM exceeds a RAM budget, or if a
//      phase stalls past a wall-clock limit. Never hang silently.
//
//  AUDIT == METRIC. Exact modular arithmetic. No floating point. Single thread.
//
//  Index convention: variables t_1..t_{n+1} are the n+1 "free" exponents
//  (slots 0..n in arrays). Original index 0 of the partition is the dependent
//  one (t_0 = (t_1...t_{n+1})^{-1}); the pair containing original index 0 is
//  dropped from rho_J exactly as in v2 (validated).
//  A basis monomial = exponent vector a[0..n], 0<=a[i]<=m-2, encoded mixed-radix
//  base B=m-1:  id = sum a[i]*B^i.
// =====================================================================
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include <unordered_map>
#include <algorithm>
#include <cstdint>
#include <string>
#include <ctime>
using namespace std;

static int n, m, d, NV, B, P;
static long long DIM;
static vector<long long> powB;
static double WALL_LIMIT = 540.0;   // 9 min phase guard (regla de los 10 min)
static long long RAM_BUDGET_VEC = 6000000LL; // max stored nonzeros across pivots (~tunable)

static inline int ad(int a,int b){ a+=b; if(a>=P)a-=P; return a; }
static inline int sb(int a,int b){ a-=b; if(a<0)a+=P; return a; }
static inline int ml(long long a,long long b){ return (int)((a*b)%P); }
static int inv(int a){ int r=1,e=P-2,b=a%P; if(b<0)b+=P; while(e){ if(e&1)r=ml(r,b); b=ml(b,b); e>>=1; } return r; }

// ---- partitions of {0..n+1} into d+1 unordered pairs, j0=0 fixed ----
static vector<vector<pair<int,int>>> parts;
static void genParts(vector<int>& av, vector<pair<int,int>>& cur){
    if(av.empty()){ parts.push_back(cur); return; }
    int a=av[0];
    for(size_t bi=1; bi<av.size(); ++bi){ int b=av[bi]; vector<int> nx;
        for(size_t i=1;i<av.size();++i) if((int)i!=(int)bi) nx.push_back(av[i]);
        cur.push_back({a,b}); genParts(nx,cur); cur.pop_back(); }
}

// ---- reduction of single-variable powers t^k into basis {1,t,...,t^{m-2}} ----
// phi(t)=0 => t^{m-1} = -(1+t+...+t^{m-2}). Precompute t^k for k in [0, 2(m-2)].
static vector<vector<pair<int,int>>> redPow;
static void buildRed(){
    int mk=2*(m-2)+1; if(mk<m)mk=m; redPow.assign(mk+1,{});
    for(int k=0;k<=m-2;k++) redPow[k]={{k,1}};
    { vector<pair<int,int>> r; for(int j=0;j<=m-2;j++) r.push_back({j,P-1}); redPow[m-1]=r; }
    for(int k=m;k<=mk;k++){ vector<int> acc(m-1,0);
        for(auto& pr:redPow[k-1]){ int e=pr.first+1,cf=pr.second;
            if(e<=m-2) acc[e]=ad(acc[e],cf);
            else for(int j=0;j<=m-2;j++) acc[j]=ad(acc[j],ml(cf,P-1)); }
        vector<pair<int,int>> r; for(int j=0;j<=m-2;j++) if(acc[j]) r.push_back({j,acc[j]});
        redPow[k]=r; }
}

// ---- SPARSE element: sorted vector of (colIndex, coef) ----
typedef vector<pair<long long,int>> SVec;

static inline void svClean(SVec& v){ // sort by col, merge, drop zeros
    sort(v.begin(),v.end());
    SVec o; o.reserve(v.size());
    for(auto& pr: v){
        if(!o.empty() && o.back().first==pr.first){ o.back().second=ad(o.back().second,pr.second); }
        else o.push_back(pr);
    }
    SVec o2; o2.reserve(o.size());
    for(auto& pr:o) if(pr.second) o2.push_back(pr);
    v.swap(o2);
}

// single-pair factor rho(t_vj, t_vk) as map: (exp_vj in 0..m-2, exp_vk in 0..m-2)->coef
// rho(x,y)=sum_{a=0}^{m-2} x^a sum_{b=0}^{a} y^b. Coef of x^a y^b = 1 if b<=a else 0.
// Returns list of (a,b) pairs (all coef 1).
static vector<pair<int,int>> rhoPairFactor(){
    vector<pair<int,int>> f;
    for(int a=0;a<=m-2;a++) for(int b=0;b<=a;b++) f.push_back({a,b});
    return f;
}

// Build rho_J TENSORIALLY as SVec. Pairs are over free variables (slots 0..n).
// Each pair contributes exponents on its two slots; all other slots have exp 0.
// Because pairs are disjoint, we accumulate the mixed-radix id by adding
// pairExp*powB[slot]. Cartesian product over the d active pairs (pair with index0 dropped).
static SVec buildRhoJ_tensor(const vector<pair<int,int>>& Pj){
    // collect active pairs (exclude the one containing original index 0)
    // map original index i -> slot: i>=1 -> slot i-1. index 0 has no slot.
    vector<pair<int,int>> apairs; // (slotA, slotB)
    for(auto& pr:Pj){
        if(pr.first==0||pr.second==0) continue;
        apairs.push_back({pr.first-1, pr.second-1});
    }
    static const vector<pair<int,int>> fac = rhoPairFactor(); // shared shape
    // start with single zero-exponent term, id=0, coef=1
    SVec cur; cur.push_back({0LL,1});
    for(auto& ap: apairs){
        long long wA=powB[ap.first], wB=powB[ap.second];
        SVec nxt; nxt.reserve(cur.size()*fac.size());
        for(auto& term: cur){
            long long baseId=term.first; int c=term.second;
            for(auto& f: fac){
                long long id = baseId + (long long)f.first*wA + (long long)f.second*wB;
                nxt.push_back({id, c}); // coef of factor is 1
            }
        }
        cur.swap(nxt);
    }
    if(apairs.empty()){ cur.clear(); cur.push_back({0LL,1}); } // d=0 edge
    svClean(cur);
    return cur;
}

// multiply a sparse element by t_var^1 (shift), reducing via redPow. var in 0..n.
static SVec shiftVar(const SVec& v, int var){
    long long w=powB[var];
    SVec out; out.reserve(v.size());
    for(auto& pr: v){
        long long id=pr.first; int cf=pr.second;
        // extract current exponent of var
        long long hi = id / w;            // ... contains var-digit as lowest digit of hi
        int e = (int)(hi % B);
        long long rest = id - (long long)e*w; // id with var-exponent zeroed
        int nk = e+1;
        // reduce t_var^{nk}
        for(auto& rp: redPow[nk]){
            long long nid = rest + (long long)rp.first * w;
            out.push_back({nid, ml(cf, rp.second)});
        }
    }
    svClean(out);
    return out;
}

// ---- sparse incremental Gaussian elimination ----
// pivots: pivotRow indexed; pivotOfCol[col] = index into pivots, or -1.
struct Reducer {
    unordered_map<long long,int> pivotOfCol; // col -> pivot id
    vector<SVec> piv;                        // pivot rows, leading col coef normalized to 1
    long long stored_nz=0;
    // reduce v against pivots; if nonzero remainder, store as new pivot; return true if new pivot added
    bool reduce_and_add(SVec v){
        // repeatedly eliminate leading entries that have pivots
        while(true){
            // find leading (smallest col) nonzero
            if(v.empty()) return false;
            // v is kept sorted by svClean; leading is v[0]
            long long lc=v[0].first;
            auto it=pivotOfCol.find(lc);
            if(it==pivotOfCol.end()) break;
            // eliminate: v -= v[0].coef * piv[it]
            const SVec& pr=piv[it->second];
            int factor=v[0].second; // pr leading coef is 1
            // v = v - factor*pr  (merge)
            SVec res; res.reserve(v.size()+pr.size());
            size_t i=0,j=0;
            while(i<v.size() && j<pr.size()){
                if(v[i].first<pr[j].first){ res.push_back(v[i++]); }
                else if(v[i].first>pr[j].first){ res.push_back({pr[j].first, sb(0, ml(factor,pr[j].second))}); j++; }
                else { int nc=sb(v[i].second, ml(factor,pr[j].second)); if(nc) res.push_back({v[i].first,nc}); i++; j++; }
            }
            while(i<v.size()) res.push_back(v[i++]);
            while(j<pr.size()){ res.push_back({pr[j].first, sb(0,ml(factor,pr[j].second))}); j++; }
            v.swap(res);
        }
        if(v.empty()) return false;
        // normalize leading to 1
        int iv=inv(v[0].second);
        for(auto& pr:v) pr.second=ml(pr.second,iv);
        long long lc=v[0].first;
        pivotOfCol[lc]=piv.size();
        stored_nz += v.size();
        piv.push_back(std::move(v));
        return true;
    }
    long long rank() const { return (long long)piv.size(); }
};

static double now_s(){ return (double)clock()/CLOCKS_PER_SEC; }

// compute dim B_K over current P. Returns -1 on guard abort.
static long long dimBK(const char* phase, FILE* logf){
    buildRed();
    Reducer R;
    double t0=now_s();
    // seed: all rho_J (tensorial)
    for(size_t pi=0; pi<parts.size(); ++pi){
        SVec rj=buildRhoJ_tensor(parts[pi]);
        R.reduce_and_add(std::move(rj));
        if(now_s()-t0>WALL_LIMIT){ if(logf) fprintf(logf,"GUARD_ABORT seeding %s\n",phase); return -1; }
    }
    // closure under variable shifts: BFS over pivot set applying t_var, until rank stable
    // We process a queue of rows; each new pivot spawns shifts.
    // To bound memory we cap stored_nz.
    vector<SVec> frontier = R.piv; // copy current pivots as frontier
    while(!frontier.empty()){
        vector<SVec> next;
        for(auto& row: frontier){
            for(int var=0; var<NV; ++var){
                SVec s=shiftVar(row,var);
                long long before=R.rank();
                bool added=R.reduce_and_add(std::move(s));
                if(added){
                    next.push_back(R.piv.back());
                }
                if(R.stored_nz>RAM_BUDGET_VEC){ if(logf) fprintf(logf,"GUARD_ABORT ram %s nz=%lld\n",phase,R.stored_nz); return -1; }
                if(now_s()-t0>WALL_LIMIT){ if(logf) fprintf(logf,"GUARD_ABORT wall %s\n",phase); return -1; }
            }
        }
        frontier.swap(next);
        if(R.rank()>=DIM) break; // full rank, quotient 0
    }
    return DIM - R.rank();
}

int main(int argc,char**argv){
    if(argc<3){ fprintf(stderr,"usage: %s n m [wall_sec]\n",argv[0]); return 1; }
    n=atoi(argv[1]); m=atoi(argv[2]); d=n/2; NV=n+1; B=m-1;
    if(argc>=4) WALL_LIMIT=atof(argv[3]);
    powB.assign(NV+1,1); for(int i=1;i<=NV;i++) powB[i]=powB[i-1]*B; DIM=powB[NV];

    vector<int> all; for(int i=0;i<n+2;i++) all.push_back(i); vector<pair<int,int>> cur; genParts(all,cur);

    string home=getenv("HOME")?getenv("HOME"):".";
    char fn[512]; snprintf(fn,sizeof(fn),"%s/Downloads/HODGE_ENGINE_v3_n%d_m%d.txt",home.c_str(),n,m);
    FILE* f=fopen(fn,"w"); if(!f){ snprintf(fn,sizeof(fn),"HODGE_ENGINE_v3_n%d_m%d.txt",n,m); f=fopen(fn,"w"); }

    // dim over C: large prime coprime to m
    int P0=1000003; while(m%P0==0) P0+=1;
    P=P0; long long dC=dimBK("C", f);

    vector<int> primes; { int mm=m; for(int p=2;p*(long long)p<=mm;p++){ if(mm%p==0){ primes.push_back(p); while(mm%p==0)mm/=p; } } if(mm>1) primes.push_back(mm); }
    string verdict="PRIMITIVE"; vector<pair<int,long long>> dp; bool aborted=(dC<0);
    if(!aborted) for(int p:primes){ P=p; long long dpp=dimBK("p", f); if(dpp<0){aborted=true;break;} dp.push_back({p,dpp}); if(dpp!=dC) verdict="TORSION"; }

    fprintf(f,"HODGE_ENGINE_v3 (sparse tensorial)\n");
    fprintf(f,"Fermat X_%d^%d : sum_{i=0}^{%d} x_i^%d = 0   dim n=%d  degree m=%d  d=n/2=%d\n",n,m,n+1,m,n,m,d);
    fprintf(f,"Method: Degtyarev-Shimada computational criterion (arXiv:1405.4683 Sec.5)\n");
    fprintf(f,"timestamp=%ld\n",(long)time(0));
    fprintf(f,"num_partitions=%zu\n",parts.size());
    fprintf(f,"dim_Rbar=(m-1)^(n+1)=%lld\n",DIM);
    if(aborted){
        fprintf(f,"VERDICT=ABORTED_BY_GUARD (case too large for current budget; not a math result)\n");
        printf("n=%d m=%d DIM=%lld => ABORTED_BY_GUARD\n",n,m,DIM);
    } else {
        fprintf(f,"dim_C  B_K = %lld\n",dC);
        for(auto& pr:dp) fprintf(f,"dim_F%d B_K = %lld\n",pr.first,pr.second);
        fprintf(f,"primes_dividing_m:"); for(int p:primes) fprintf(f," %d",p); fprintf(f,"\n");
        fprintf(f,"VERDICT=%s\n",verdict.c_str());
        if(verdict=="PRIMITIVE") fprintf(f,"=> L(X) primitive. Standard linear cycles GENERATE the integral Hodge lattice.\n");
        else fprintf(f,"=> torsion present (order divides m). Linear cycles do NOT generate integrally. CANDIDATE special case.\n");
        printf("n=%d m=%d DIM=%lld dimC=%lld",n,m,DIM,dC);
        for(auto&pr:dp) printf(" dim_%d=%lld",pr.first,pr.second);
        printf(" => %s\n",verdict.c_str());
    }
    fclose(f);
    return aborted?2:0;
}
